### ISSUE TITLE
Questions about Navtrain Dataset and warmup_test

### ISSUE THREAD

**Issue by sakjdas** [autonomousvision/navsim#11]
Hi everyone, I notice that there was an update in the navsim repository including dataset, new baseline, visualizations, thanks for the great work. I have a question about the navtrain dataset, when I downloaded it, it seemed there is no current_split_5 and history_split_5,   which included in the download script(as shown below). Did I miss something or there is no such data? And there is no corrresponding pkl file, which means we can't use it for our training, will it be provided later?

![image](https://github.com/autonomousvision/navsim/assets/95308124/665bcc38-f06b-4299-af5e-11773f67ce76)

Another Question is that privously I split the mini set into train, val, test for small testing, and upload the trained model on the warmup track. But I notice that you said that the warmup_test_e2e is a scene filter for the mini split. So can I ask which part of the mini set you use for the warmup track? 

Thanks a lot for answering my question!

**Comment by mh0797** [comment]
Hi @sakjdas,

Thanks for your feedback. Please find the answers to your questions below.

### Missing files when downloading navtrain
Thanks for pointing out that the files `current_split_5.tgz` and `history_split_5.tgz` are missing on the aws download server. We will look into this and come back to you.

### Why is there no pickle file for Navtrain data?
As described in the [docs](https://github.com/autonomousvision/navsim/blob/main/docs/splits.md), Navtrain is just a fraction of trainval that was obtained by filtering it for challenging scenarios. Moreover, it also includes overlapping scenes, while trainval consists only of non-overlapping scenes.
Then Navtrain download script, simply loads the sensor data for these filtered scenes.
As Navtrain is a fraction of trainval, no additional `.pkl` file is needed for the logs, since all the scenes are already included in the `.pkl` file for trainval (which is not very large). So you can just download the `.pkl` file for trainval. 
With that being said, given that the file is small, we might add it to the download script to make the setup even more convenient. Thus, thanks for your feedback.

### Current vs. History Frames
The script to load Navtrain downloads sensor-data for `current` and `history` frames. While `current` means the sensor data for `t=0` of each scenes, `history` refers to the sensor data of past timesteps. Consequently, if you want to run an agent, that does not need access to past sensor data, you don't need the `history` sensor data.

### How is `mini` split into train, val, test ?
`mini` is a dataset-split that contains log files for training, validation and testing. Our training pipeline automatically ensures, that the respective logs are loaded into the training and validation data loaders (see [splitter](https://github.com/autonomousvision/navsim/blob/main/navsim/planning/script/config/training/default_train_val_test_log_split.yaml)). So if so far you used `split=mini` and `scene_filter=all_scenes`(which is the default) for training, then you trained on these logs. The test-logs of mini are left untouched in training.

### test-logs in `mini` vs. warmup_test_e2e
The warmup_test_e2e scene-filter filters the test-logs from the `mini` dataset for challenging scenarios by employing the same strategy that is used to generate navtrain from trainval. Thus it subsamples these logs.


Let me know if this answers your questions.

**Comment by sakjdas** [comment]
Thank you for your patient replies; they have addressed all of my questions!

**Comment by DanielDauner** [comment]
Hey @sakjdas, we don’t have a `current_split_5` or `history_split_5`. It was a bug in the for-loop of the download script. Thanks for pointing this out! 

We updated the `download_navsim.sh` script, which additionally downloads the logs now. 

Best, Daniel
