### ISSUE TITLE
The impact of caching to training

### ISSUE THREAD

**Issue by sakjdas** [autonomousvision/navsim#13]
Hi, when i move to the whole dataset and use run_dataset_caching to cache the trainval data, it takes almost 16 hours to cache all the data. For features, I **only use ego_state and front images** by now. I am not sure how long  it takes when i move to all the images and all the lidar data. **And it also means when i want to change my input, i will have to cache all the data again.** So I want to ask are there anyway to **accelerate the caching process**, or are there anyway that i can **directly start training** instead of caching the data for more than one day (probably without losing too much performance)? Did I miss something? below is the script I use when cache the data:

![image](https://github.com/autonomousvision/navsim/assets/95308124/c46ec351-bf31-42e2-b6fd-58c24da2861f)

by the way I have num_workers = 96, and also with GPU memory = 24GB * 2, are there anyway I can fully make use of it to acc the training process?

Thanks in advance

**Comment by mh0797** [comment]
Hi @sakjdas,
## Why do we need dataset caching
Navsim loads the openscene data into `scene` objects. The feature- and target-builders of the agent then compute the tensors used for training from them. To speed up training, we cache all the tensors. This speeds up training by a margin.

## Can I run the training without dataset caching?
It is possible to run the `run_training.py` script without running `run_dataset_chaching.py` before. In this case, the training dataloaders will recognize that the tensors cannot be loaded from cached files. Thus, they will generate the cache before starting the training. However, this is much slower than caching everything before training.

## Do I need to generate a new cache if I update the features/targets my model uses?
Yes. Features and targets are stored as pickle files with the name set in the respective feature / target-builder.
When running a training / dataset-caching, the dataloader first checks if the features/targets to be computed already exist by checking if the file with the respective name exists. If there is an old cache (with a previous version of your features/targets), these will be loaded instead of re-computing. 
You can prevent this behavior by setting `force_feature_computation=true`: this will overwrite an existing cache.
In any case, the features/targets must be computed and stored again, i.e., a new cache must be generated.

## The caching is slow. How can I speed it up?
Use the `run_dataset_caching.py` script (it can be used with the same overrides as the `run_training.py` script).
This has two benefits. First, it runs the caching without performing a forward pass through the model for each feature. Second, it does not use a single dataloader but instead creates several workers, each of which processes a split of the data with its own dataloader. To effectively use this option, make sure not to use an override for `worker.threads_per_node`. This will set the number of workers equal to the number of CPUs available. Second, I recommend not touching `dataloader.params.num_workers` because if each of the created dataloaders spawns many workers, this can lead to issues and slow down the caching.
(Also, you might want to set the batch_size to 1 to reduce memory demands).

## The caching is still too slow. What can I do?
Navtrain consists of ~100k scenes. Therefore, making the feature-/target-builders more efficient greatly impacts the runtime. Also, reducing the size of the computed tensors can reduce the runtime, as pickling them will be faster.


Hope this helps. Feel free to re-open the issue if you have more questions.

Best
Marcel
