### ISSUE TITLE
What is the starting point of PDM-Closed trajectory?

### ISSUE THREAD

**Issue by efemantarci** [autonomousvision/navsim#24]
So there is a trajectory stored in metric cache data. I am trying to look to the path it takes but I couldn't figure out where does it start ?
Is the start position initial_ego_state.center ?

**Comment by DanielDauner** [comment]
The PDM-Planner starts either on the centerline or has a lateral offset of ± 1m. We discussed this [#12](https://github.com/autonomousvision/tuplan_garage/issues/12) of the [`tuplan_garage`](https://github.com/autonomousvision/tuplan_garage/) repository. Agents in NAVSIM (1) output a trajectory of local coordinates (with the rear axle being the origin) that are (2) converted into global coordinates, where (3) the initial position is added to the trajectory (see [here](https://github.com/autonomousvision/navsim/blob/main/navsim/evaluate/pdm_score.py#L24)).

I hope that helps! Otherwise, feel free to re-open.

**Comment by lsm2842035890** [comment]
/navsim-1.1/navsim/planning/script/run_pdm_score.py I would like to know what frequency the script requires the agent to output the future eight-second trajectories? Is it 1Hz = 8 trajectories or 2Hz = 16 trajectories?Can this script set the frequency to meet different evaluation requirements? Or where can I set the number of waypoints needed for the evaluation?
