### ISSUE TITLE
UniAD agent implementation

### ISSUE THREAD

**Issue by ihjasahammedm** [autonomousvision/navsim#25]
Hi team,
Benchmark evaluation for UniAD is present in the paper, Is there any plan for releasing UniAD agent implementation?
Can you tell us how did you evaluate UniAD on the navsim benchmark?

Thank you.

**Comment by sephyli** [comment]
Hi, thanks for your question.

Both PARA-Drive and UniAD are implemented in the same codebase. This part of the code will be released in a separate repository. We are currently awaiting approval from the legal teams of our industry partners before proceeding with the release.

Regarding the implementation details, we will update them in the next version of the arXiv paper, including the appendix, soon. Please stay tuned.

**Comment by ihjasahammedm** [comment]
Thank you for the information.

**Comment by MPCheng-ZW** [comment]
Hi, great job! When do you plan to release the code of UniAD implementation on the NavSim?  Thanks~ @sephyli

**Comment by owl-10** [comment]
> Hi, thanks for your question.
> 
> Both PARA-Drive and UniAD are implemented in the same codebase. This part of the code will be released in a separate repository. We are currently awaiting approval from the legal teams of our industry partners before proceeding with the release.
> 
> Regarding the implementation details, we will update them in the next version of the arXiv paper, including the appendix, soon. Please stay tuned.

@sephyli Thanks for the update. May I ask if you plan to release the latest UniAD implementation soon?

**Comment by sephyli** [comment]
@owl-10 
This issue has indeed been delayed for quite some time.
First, unfortunately, the UniAD implementation used in the NAVSIM paper is derived from PARA Drive, which means the related code can only be released after PARA Drive obtains NVIDIA’s open-source license (which is highly likely to be resolved within this year).

Over the past year, we have updated the UniAD repository itself to match newer versions of PyTorch and MMDet3D. In the near future, we will release an update to the UniAD repository that fixes many hard-coded coordinate conversions and other bugs, preparing it for compatibility with the NAVSIM dataset.

I believe that once PARADrive is open-sourced, we will quickly release a UniAD version that supports NAVSIM. Moreover, due to the numerous bug fixes, this version is expected to achieve even better performance.
