### ISSUE TITLE
How to get fine routes?

### ISSUE THREAD

**Issue by yanglong2000** [autonomousvision/navsim#38]
Dear Author.

I tried to use a script to get the routes and visualize them as shown in the image, but the routes are too coarse. Can you provide a script to get the fine routes.

Also, is it possible to get driving commands via route?

Thank you very much for your help.
...

    def _get_route_from_roadblocks(self) -> npt.NDArray:
        road_level_route = []
        map_api = self._initialization.map_api
        for roadblock_id in self._initialization.route_roadblock_ids:
            potential_result = map_api._get_roadblock(roadblock_id)
            if potential_result is None:
                centroid = None
            else:
                centroid = potential_result._get_roadblock().geometry.centroid
            if centroid: road_level_route.append([centroid.x, centroid.y])

        road_level_route = np.array(road_level_route)
        return road_level_route
...

![20241120-110001](https://github.com/user-attachments/assets/68dda466-fc61-4ff5-a789-d86e8467c68d)

**Comment by DanielDauner** [comment]
Hi @yanglong2000,

The routes are provided as a sequence of roadblocks, which are a collection of lanes that travel in the same direction. There is no straightforward way how to retrieve a finer route. You can adapt the visualization to plot the roadblock polygons (instead of the centroids) in a specific color to get a better idea of the route provided in nuPlan/OpenScene. Our [visualization script](https://github.com/autonomousvision/navsim/blob/main/navsim/visualization/bev.py) has examples of how to plot polygons.

The driving command is based on the route roadblock sequence. We first search with a Dijkstra Algorithm to get a specific sequence of lanes to drive along. We then extract the baseline paths of the lanes and merge them in a single route centerline. Depending on the centerline curvature, we determine whether the command is left, straight, or right. This is more clearly described in our [supplementary material](https://danieldauner.github.io/assets/pdf/Dauner2024NIPS_supplementary.pdf), and the code can be found [here](https://github.com/OpenDriveLab/OpenScene/blob/main/DriveEngine/process_data/helpers/driving_command.py).

I hope that helps!
Daniel
