### ISSUE TITLE
Use nuScenes dataset instead of OpenScene

### ISSUE THREAD

**Issue by dentou** [autonomousvision/navsim#42]
Because it was written in the paper that
> The NAVSIM framework is agnostic to the choice of driving dataset.

I would like to ask if it is possible to use NAVSIM framework with nuScenes dataset instead of OpenScene. If it is possible, what should I do to add nuScenes to this code base?

Thank you.

**Comment by mh0797** [comment]
Hi,

As stated in the paper, it is possible to use other datasets to evaluate a driving agent by rolling out its trajectory with a controller and bicycle model and subsequently evaluating the outcome with planning-oriented metrics rather than displacement errors.

This navsim-devkit only supports the openscene dataset which is based on nuPlan. If you want to extend it to also run nuScenes, there are two ways to approach this:

1. Convert nuScenes into the openscene data format.
You might find the [openscene repo](https://github.com/OpenDriveLab/OpenScene/tree/main) helpful as it contains code that converts nuPlan into the openscene format. Note that you will also need to convert the maps into a format that can be read by the nuPlan map-api.

2. Implement your own dataloader.
Alternatively, you can implement an additional dataloader that can directly read the nuScenes dataset and build navsim Scenes from it. As the navsim [Scenarios](https://github.com/autonomousvision/navsim/blob/main/navsim/planning/scenario_builder/navsim_scenario.py) used for metric caching require a compatible map in addition to the navsim Scene, you will need to implement a custom navsim Scenario compatible with the nuScenes map format.

**Comment by dingli-dean** [comment]
Hi

> Because it was written in the paper that
> 
> > The NAVSIM framework is agnostic to the choice of driving dataset.
> 
> I would like to ask if it is possible to use NAVSIM framework with nuScenes dataset instead of OpenScene. If it is possible, what should I do to add nuScenes to this code base?
> 
> Thank you.

Hello, have you tried to apply navsim framework with nuScenes or other dataset?
