### ISSUE TITLE
Question About Navtest Splits

### ISSUE THREAD

**Issue by BlueCat-de** [autonomousvision/navsim#44]
Hi!
How can I download the navtest dataset? Thanks!

**Comment by BlueCat-de** [comment]
Is navtest the same as standard test split?

**Comment by mh0797** [comment]
Hi @BlueCat-de,

Navtest is a subset of the standard test split. Thus, navtest and test are not identical!
However, due to the moderate size of the (full) standard test split, we do not provide navtest as a separate download.
You can use the script provided to download the full test split and then run experiments setting `train_test_split=navtest`.

Best
Marcel
