### ISSUE TITLE
run_metric_caching.sh error on test split

### ISSUE THREAD

**Issue by ucwxb** [autonomousvision/navsim#5]
The script processes the mini set successfully but fails on test split with key error 'anns'.
![image](https://github.com/autonomousvision/navsim/assets/29229101/c9d55fd4-eeeb-457c-9712-5b2e2cdbdebb)

**Comment by mh0797** [comment]
Hi @ucwxb ,
this is unfortunately an issue with the test dataset that has been uploaded to huggingface.
We are aware of this and in the process of uploading a fixed version of the dataset.
In the meantime, We recommend to run training / evaluation on the mini split.

I will follow-up here, once the new version of the dataset is pushed.

Sorry for any inconvenience.

**Comment by ucwxb** [comment]
> Hi @ucwxb , this is unfortunately an issue with the test dataset that has been uploaded to huggingface. We are aware of this and in the process of uploading a fixed version of the dataset. In the meantime, We recommend to run training / evaluation on the mini split.
> 
> I will follow-up here, once the new version of the dataset is pushed.
> 
> Sorry for any inconvenience.

Thanks for your reply!
And I also notice that the process still fails on trainval set:
![image](https://github.com/autonomousvision/navsim/assets/29229101/2a7dbda4-bce6-4d94-924e-41f466956b96)

**Comment by ucwxb** [comment]
Additionally, when I run the default run_cv_pdm_score_evaluation.sh on the mini split, a series of AssertionError occur. Is this normal? Do I need to further supplement the agent part of the code?
![image](https://github.com/autonomousvision/navsim/assets/29229101/b9abf039-5b30-40c3-8721-1c8557a9c534)

The front part of the log appears to be normal, but the later scenes have no values and display false.
![image](https://github.com/autonomousvision/navsim/assets/29229101/bbca0f6e-31db-4136-9555-a3e47f815253)
![image](https://github.com/autonomousvision/navsim/assets/29229101/a582e1ac-6d1a-4f20-ab41-783b4d28ad74)

**Comment by mh0797** [comment]
Hi,
I assume you mean the `mini` split as we haven't published the `trainval` split yet.
Can you please share which version of the dataset you are using to run the metric caching (i.e., when and how did you download it)?

**Comment by mh0797** [comment]
Hi,
thanks for the clarification. The devkit does not yet officially support the `trainval` set since we first need to handle some annotation issues in the original `trainval` split. Hence, the behavior you see is somewhat expected, i.e., for some scenes the metric cache cannot be generated due to route annotation issues. In consequence, the evaluation will fail for these tokens, which is why you see the assertion error. Thus, for these tokens, the CSV contains no results and the second column (that describes if the results for this token are valid) is set to `False`.

We will soon release the next version of the devkit together with the `trainval` dataset on huggingface.

However, as far as I can see, you still get valid results for the remaining Scenes (see the "front part" of your CSV).
So, in the meantime, you could still run your agent on the `trainval` split, but be aware that results might change slightly once we address all the dataset issues.

I am closing this issue for now. Feel free to re-open or open a new issue once you face more problems.

**Comment by ucwxb** [comment]
Thanks for your reply!

**Comment by mh0797** [comment]
Hi,
we uploaded the corrected version of the test dataset (which includes the annotations). 
You can download it directly from Huggingface or with the download script.

Besides, the latest fix we pushed today should solve the issue you had with the trainval set (however, no guarantee yet that everything works as its not officially supported yet).

**Comment by ucwxb** [comment]
> Hi, we uploaded the corrected version of the test dataset (which includes the annotations). You can download it directly from Huggingface or with the download script.
> 
> Besides, the latest fix we pushed today should solve the issue you had with the trainval set (however, no guarantee yet that everything works as its not officially supported yet).

Thank you for your timely reply. Please let me know when all datasets are ready. Thanks!
