### ISSUE TITLE
Can we access the lidar2ego and lidar2global matrixs in private test set？

### ISSUE THREAD

**Issue by ucwxb** [autonomousvision/navsim#7]

**Comment by mh0797** [comment]
Hi @ucwxb,
we do not provide these as part of the agent input in the private test set, as otherwise it would be possible to infer the map location and thus use HD map information.

Therefore, the poses in the agent input are already represented in the local ego frame (the global frame is chosen to coincide with the ego frame). Hence, there is no need to transform them anymore as the transformation lidar2ego and lidar2globak would simply be an identity function.
