### ISSUE TITLE
About the negative origin.heading in convert_absolute_to_relative_se2_array

### ISSUE THREAD

**Issue by ucwxb** [autonomousvision/navsim#9]
Could someone please explain why the heading angle needs to be set to negative in the function convert_absolute_to_relative_se2_array？https://github.com/autonomousvision/navsim/blob/800cbd199bbfe31012c61a73d5b0af435af6aa87/navsim/planning/simulation/planner/pdm_planner/utils/pdm_geometry_utils.py#L92
Thanks！

**Comment by DanielDauner** [comment]
Hi, the function transforms all poses in `state_se2_array` into the coordinate frame of `origin`. [This line](https://github.com/autonomousvision/navsim/blob/800cbd199bbfe31012c61a73d5b0af435af6aa87/navsim/planning/simulation/planner/pdm_planner/utils/pdm_geometry_utils.py#L97) subtracts the `origin` from `state_se2_array` to translate the points and adjust the headings. Next, we need to rotate the translated points by the negative angle of `origin` (i.e., revert the rotation of the global frame). The negative angle cancels out the global frame's heading angle of `origin`. 

You can avoid the negative angle and re-write the rotation matrix `R` since $sin(-\theta)=-sin(\theta)$ and $cos(-\theta)=cos(\theta)$.

Best, Daniel
